#red-square-block: 'RED_CONCRETE'
#black-square-block: 'BLACK_CONCRETE'
#p1-piece-block: 'ACACIA_FENCE'
#p2-piece-block: 'DARK_OAK_FENCE'
#selected-piece-block: 'BIRCH_FENCE'
#king-block: 'CREEPER_HEAD'
red-square-block: ''
black-square-block: ''
p1-piece-block: ''
p2-piece-block: ''
selected-piece-block: ''
king-block: ''